// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vijdogwqfqrgqmdjqgev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpamRvZ3dxZnFyZ3FtZGpxZ2V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDA2MTUsImV4cCI6MjA2NjY3NjYxNX0.WdJwGeyq2ZvWNskgwqAKACXFNlU9Hnhsg5iRR3I9W-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});